apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/you/orders-app-repo.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
        - values-minikube.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
