apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jyengue1/app-of-apps-gitops.git
    targetRevision: 
    path: apps/payments/chart
    helm:
      valueFiles:
        - values.yaml
        - values-minikube.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
